export default {

    getApiHost() {
        return API_HOST;
    },

    GET_STORES_ACTION: "GET_STORES_ACTION",
    GET_BROCHURE_DETAILS_ACTION: "GET_BROCHURE_DETAILS",
    GET_BROCHURES_ACTION: "GET_BROCHURES",

    GET_STORES_EVENT: "GET_STORES_EVENT",
    GET_BROCHURE_DETAILS_EVENT: "GET_BROCHURE_DETAILS_EVENT",
    GET_BROCHURES_EVENT: "GET_BROCHURES_EVENT"
};